# Generated by Django 4.2.2 on 2023-06-20 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=10)),
                ('height', models.FloatField(verbose_name='Height in Ft.')),
                ('weight', models.FloatField(verbose_name=' Weight in Kg')),
                ('dob', models.DateField()),
                ('profile_pic', models.ImageField(upload_to='profilepic/')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
