# Generated by Django 4.2.2 on 2023-06-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_userdetail_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='first_name',
            field=models.CharField(default='S-sewa', max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='last_name',
            field=models.CharField(default='User', max_length=255),
        ),
    ]
