# Generated by Django 4.1.6 on 2023-03-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='prescription',
            field=models.TextField(null=True),
        ),
    ]
