# Generated by Django 4.1.6 on 2023-03-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_healthrecord_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
